import json
import os
import pandas as pd
import mplfinance as mpf # הספרייה הכבדה לגרפים
from datetime import datetime

DATA_DIR = "data"
CHARTS_DIR = "charts"
SITE_URL = "https://almog787.github.io/Stock-information-/"

if not os.path.exists(CHARTS_DIR): os.makedirs(CHARTS_DIR)

def create_pro_chart(json_path, symbol, score):
    with open(json_path, 'r') as f:
        data = json.load(f)
    
    # המרה ל-DataFrame של פנדס עם אינדקס תאריך (חובה ל-mplfinance)
    df = pd.DataFrame(data['history'])
    df['Date'] = pd.to_datetime(df['Date'])
    df.set_index('Date', inplace=True)
    
    # חיתוך לחצי שנה אחרונה כדי שהנרות ייראו ברור
    df = df.tail(120)

    # הגדרת תוספות לגרף (Addplots)
    # EMA 50 ו-EMA 200
    apds = [
        mpf.make_addplot(df['EMA_50'], color='#2962ff', width=1.5),
        mpf.make_addplot(df['EMA_200'], color='#ff6d00', width=1.5),
    ]

    # סגנון הגרף (Dark Theme מותאם אישית)
    market_style = mpf.make_mpf_style(
        base_mpf_style='nightclouds', 
        marketcolors=mpf.make_marketcolors(up='#00ff41', down='#ff003c', edge='inherit', wick='inherit', volume='in'),
        gridstyle=':', 
        rc={'axes.edgecolor': '#333', 'font.size': 10}
    )

    # שמירת התמונה
    filename = f"{CHARTS_DIR}/{symbol}.png"
    
    mpf.plot(
        df,
        type='candle',
        style=market_style,
        addplot=apds,
        volume=True,
        title=f"\n{symbol} - AI Score: {score}/100",
        savefig=dict(fname=filename, dpi=100, bbox_inches='tight'),
        figsize=(12, 6)
    )
    print(f"Generated Pro Chart for {symbol}")

def generate_markdown():
    rankings_path = os.path.join(DATA_DIR, "market_rankings.json")
    if not os.path.exists(rankings_path): return

    with open(rankings_path, 'r') as f:
        rankings = json.load(f)
    
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    
    md = f"""# 🧠 Institutional AI Market Radar
**Powered by `pandas-ta` & `mplfinance`**

## 🚀 [Access Live Terminal]({SITE_URL})

> **System Status:** 🟢 Online | **Last Scan:** {now}

## 📊 Top 3 Asset Analysis (Candlestick View)
"""
    
    # יצירת גרפים רק ל-3 הראשונים
    for i in range(3):
        if i < len(rankings):
            r = rankings[i]
            json_path = os.path.join(DATA_DIR, f"{r['symbol']}_daily.json")
            if os.path.exists(json_path):
                create_pro_chart(json_path, r['symbol'], r['score'])
                
                signals = ", ".join(r['signals']) if r['signals'] else "Neutral Trend"
                md += f"### {i+1}. {r['symbol']} (Score: {r['score']})\n"
                md += f"> **Signals:** {signals}\n\n"
                md += f"![{r['symbol']} Analysis](charts/{r['symbol']}.png)\n\n"

    md += """## 📋 Full Market Intelligence
| Rank | Asset | Price | Change | AI Score | Trend Strength (ADX) | Momentum (RSI) |
| :--: | :---- | :---: | :----: | :------: | :------------------: | :------------: |
"""
    
    for i, r in enumerate(rankings):
        trend = "🟢" if r['change'] > 0 else "🔴"
        score_icon = "💎" if r['score'] >= 80 else ("⚠️" if r['score'] <= 30 else "🔹")
        
        # פרשנות ADX
        adx_str = f"Strong ({r['adx']:.0f})" if r['adx'] > 25 else f"Weak ({r['adx']:.0f})"
        
        md += f"| {i+1} | **{r['symbol']}** | ${r['price']:.2f} | {trend} {r['change']:.2f}% | {score_icon} **{r['score']}** | {adx_str} | {r['rsi']:.1f} |\n"

    md += f"\n\n---\n*Analysis performed via Python pandas-ta library. Charts generated by mplfinance.*"
    
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(md)

if __name__ == "__main__":
    generate_markdown()
